name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    name: pre-commit (ruff/black/isort/mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Cache acelera instalações dos hooks
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      # Roda exatamente os hooks definidos no seu .pre-commit-config.yaml
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  tests:
    name: pytest
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # se usa layout "src", instale o pacote em modo editável:
          pip install -e .

      - name: Run tests
        run: pytest -q
